/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedCheckpointsRouteImport } from './routes/_authenticated/checkpoints'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedExportRouteImport } from './routes/_authenticated/export'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedQrCodesRouteImport } from './routes/_authenticated/qr-codes'
import { Route as AuthenticatedScanHistoryRouteImport } from './routes/_authenticated/scan-history'
import { Route as AuthenticatedScannerRouteImport } from './routes/_authenticated/scanner'
import { Route as AuthenticatedTeamsRouteImport } from './routes/_authenticated/teams'
import { Route as AuthenticatedTeamsTeamIdRouteImport } from './routes/_authenticated/teams.$teamId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckpointsRoute =
  AuthenticatedCheckpointsRouteImport.update({
    id: '/checkpoints',
    path: '/checkpoints',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExportRoute = AuthenticatedExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQrCodesRoute = AuthenticatedQrCodesRouteImport.update({
  id: '/qr-codes',
  path: '/qr-codes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScanHistoryRoute =
  AuthenticatedScanHistoryRouteImport.update({
    id: '/scan-history',
    path: '/scan-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedScannerRoute = AuthenticatedScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamsRoute = AuthenticatedTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamsTeamIdRoute =
  AuthenticatedTeamsTeamIdRouteImport.update({
    id: '/$teamId',
    path: '/$teamId',
    getParentRoute: () => AuthenticatedTeamsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/checkpoints': typeof AuthenticatedCheckpointsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/export': typeof AuthenticatedExportRoute
  '/import': typeof AuthenticatedImportRoute
  '/qr-codes': typeof AuthenticatedQrCodesRoute
  '/scan-history': typeof AuthenticatedScanHistoryRoute
  '/scanner': typeof AuthenticatedScannerRoute
  '/teams': typeof AuthenticatedTeamsRouteWithChildren
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/checkpoints': typeof AuthenticatedCheckpointsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/export': typeof AuthenticatedExportRoute
  '/import': typeof AuthenticatedImportRoute
  '/qr-codes': typeof AuthenticatedQrCodesRoute
  '/scan-history': typeof AuthenticatedScanHistoryRoute
  '/scanner': typeof AuthenticatedScannerRoute
  '/teams': typeof AuthenticatedTeamsRouteWithChildren
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/checkpoints': typeof AuthenticatedCheckpointsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/export': typeof AuthenticatedExportRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/qr-codes': typeof AuthenticatedQrCodesRoute
  '/_authenticated/scan-history': typeof AuthenticatedScanHistoryRoute
  '/_authenticated/scanner': typeof AuthenticatedScannerRoute
  '/_authenticated/teams': typeof AuthenticatedTeamsRouteWithChildren
  '/_authenticated/teams/$teamId': typeof AuthenticatedTeamsTeamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/attendance'
    | '/checkpoints'
    | '/dashboard'
    | '/export'
    | '/import'
    | '/qr-codes'
    | '/scan-history'
    | '/scanner'
    | '/teams'
    | '/teams/$teamId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/attendance'
    | '/checkpoints'
    | '/dashboard'
    | '/export'
    | '/import'
    | '/qr-codes'
    | '/scan-history'
    | '/scanner'
    | '/teams'
    | '/teams/$teamId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/attendance'
    | '/_authenticated/checkpoints'
    | '/_authenticated/dashboard'
    | '/_authenticated/export'
    | '/_authenticated/import'
    | '/_authenticated/qr-codes'
    | '/_authenticated/scan-history'
    | '/_authenticated/scanner'
    | '/_authenticated/teams'
    | '/_authenticated/teams/$teamId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkpoints': {
      id: '/_authenticated/checkpoints'
      path: '/checkpoints'
      fullPath: '/checkpoints'
      preLoaderRoute: typeof AuthenticatedCheckpointsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/export': {
      id: '/_authenticated/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AuthenticatedExportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qr-codes': {
      id: '/_authenticated/qr-codes'
      path: '/qr-codes'
      fullPath: '/qr-codes'
      preLoaderRoute: typeof AuthenticatedQrCodesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scan-history': {
      id: '/_authenticated/scan-history'
      path: '/scan-history'
      fullPath: '/scan-history'
      preLoaderRoute: typeof AuthenticatedScanHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scanner': {
      id: '/_authenticated/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof AuthenticatedScannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teams': {
      id: '/_authenticated/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AuthenticatedTeamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teams/$teamId': {
      id: '/_authenticated/teams/$teamId'
      path: '/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdRouteImport
      parentRoute: typeof AuthenticatedTeamsRoute
    }
  }
}

interface AuthenticatedTeamsRouteChildren {
  AuthenticatedTeamsTeamIdRoute: typeof AuthenticatedTeamsTeamIdRoute
}

const AuthenticatedTeamsRouteChildren: AuthenticatedTeamsRouteChildren = {
  AuthenticatedTeamsTeamIdRoute: AuthenticatedTeamsTeamIdRoute,
}

const AuthenticatedTeamsRouteWithChildren =
  AuthenticatedTeamsRoute._addFileChildren(AuthenticatedTeamsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedCheckpointsRoute: typeof AuthenticatedCheckpointsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExportRoute: typeof AuthenticatedExportRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedQrCodesRoute: typeof AuthenticatedQrCodesRoute
  AuthenticatedScanHistoryRoute: typeof AuthenticatedScanHistoryRoute
  AuthenticatedScannerRoute: typeof AuthenticatedScannerRoute
  AuthenticatedTeamsRoute: typeof AuthenticatedTeamsRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedCheckpointsRoute: AuthenticatedCheckpointsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExportRoute: AuthenticatedExportRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedQrCodesRoute: AuthenticatedQrCodesRoute,
  AuthenticatedScanHistoryRoute: AuthenticatedScanHistoryRoute,
  AuthenticatedScannerRoute: AuthenticatedScannerRoute,
  AuthenticatedTeamsRoute: AuthenticatedTeamsRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
